-- 테이블 삭제
DROP TABLE TEMP;

-- 테이블 생성
CREATE TABLE TEMP (
	NAME VARCHAR2(30),
	AGE NUMBER
);

-- 데이터 추가
INSERT INTO TEMP VALUES ('홍길동', 30);

-- 데이터 조회
SELECT * FROM TEMP;

-- SEQUENCES
CREATE SEQUENCE PROJECT_SEQ 
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CYCLE;

CREATE SEQUENCE TASK_SEQ 
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CYCLE;

CREATE SEQUENCE TIME_ENTRY_SEQ 
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CYCLE;

CREATE SEQUENCE ATTACHMENT_SEQ 
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CYCLE;

CREATE SEQUENCE COMMENTS_SEQ 
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CYCLE;

CREATE SEQUENCE NOTICE_SEQ 
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CYCLE; 

CREATE SEQUENCE ACCOUNT_SEQ 
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CYCLE; 

CREATE SEQUENCE JOURNAL_SEQ 
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CYCLE; 

CREATE SEQUENCE JOURNAL_DETAIL_SEQ 
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CYCLE; 

CREATE SEQUENCE RISK_SEQ 
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CYCLE; 


SELECT A.ID ACCOUNT_ID, A.NAME, A.AUTH,
	COUNT(CASE WHEN A.ID = T.ACCOUNT_ID THEN 1 END) TOTAL,
	COUNT(CASE WHEN T.STATUS = '완료' AND A.ID = T.ACCOUNT_ID THEN 1 END) COMPLETED, 
	COUNT(CASE WHEN T.STATUS != '완료' AND A.ID = T.ACCOUNT_ID THEN 1 END) INCOMPLETED
	FROM ACCOUNT A, TASK T GROUP BY (A.ID, A.NAME, A.AUTH) ORDER BY A.ID DESC;